---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sealed-test-secret
  namespace: default
spec:
  encryptedData:
    PASSWORD: AgB8b/3b4gAoIwTScopYhJMRJ1QZfHc6FqcnloCz6ypIDFCwNp9QQdEd+LeCEghqaUhx5tdQRgh7XGV49m/hI8DhxTtX0hV8Q/wo7aLpfu4B51gFR5Ko9IEqiFC3yZjpC/WLdmz6WB0wa1IzMd6F2+s+bZnhkbh0M16hVz818YYjGBmOtFZ5TOfsqhakN+C//Kwfo3nd2KTbDCW29SpF8LbUhFoLDJg9B4FsOC2L6WJwLOp/iQV33aa0wNRB9G1nCo0st68n01OkM2BmSaBajbwVaLY8lTwJQkGuYBMunYbiUcrp4Lcph+JpeJaH5m4OCIjB01WcVUSborgNNogDr6LkR+6FPPlkJFHnbKdAnWSXm00rinMbmU6bNsCnS72xqm/Dq/rfQVqrgmQqHTrRwjGPuc0cKuUIY67/FugdCmYaCmWo4PuFUvbYrkQYVnyEPCwTtlhyb3lgnrXNjtyWQcAt7zgRQxcOTQjjaHGfNeicF7dKQi5yBmTju01c5M4xZYNoy4Chvm+PpJjWQw2DVYdkYZWGtiqUAWfrdAx+flehRccCkJYRZWjaTzUgM78+AUWXdvkOCgVfPkTy4TAuFwxWtlsoYfNfyxALwAMc/dQyNacQcEw9hpjlcZmMzSSWzsobDT8WpfvJOn3r31gw7ESKBgn9q6pQNx0R6J8wzvlu4Ntcc7WI9Av68qp6SsZCBndCZLuzn0AHePw1
  template:
    metadata:
      creationTimestamp: null
      name: sealed-test-secret
      namespace: default
